### ISSUE TITLE
Getting Unsupported or unrecognized SSL error message

### ISSUE THREAD

**Issue by SyedsImran** [cloudamqp/amqproxy#100]
Getting ```Unsupported or unrecognized SSL message``` error message while connecting to rabbitmq through amproxy.

Used below command to setup amqp proxy. Proxy got setup successfully.

```
./amqproxy -l 5.161.156.165 -p 5673 amqps://stg.qtech.com

Command Response:
Proxy upstream: stg.qtech.com:5671 TLS
Proxy listening on 5.161.156.165:5673
0 clients		 0 upstreams

```

Consumer Command to connect to rabbitmq via amqpproxy
```
docker run --name Consumer-test -d -e HOST=5.161.156.165 -e PORT=5673 -e IAM=3456QL97KLtzIhhdWdDj1VUhipl7AOL -e KEY=wdn4Lg8IUU9jQS+TGEAOpjCN3FvBtoAnBqNtWGVIkuUm6dEmVyg== qtech/bot:latest
```
But getting below error SSL exception.

```
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175) ~[na:na]
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:915) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1285) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[na:na]
	at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128) ~[na:na]
	at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:160) ~[amqp-client-5.12.0.jar!/:5.12.0]
	at com.rabbitmq.client.impl.SocketFrameHandler.sendHeader(SocketFrameHandler.java:170) ~[amqp-client-5.12.0.jar!/:5.12.0]
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:314) ~[amqp-client-5.12.0.jar!/:5.12.0]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1222) ~[amqp-client-5.12.0.jar!/:5.12.0]
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1170) ~[amqp-client-5.12.0.jar!/:5.12.0]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connectAddresses(AbstractConnectionFactory.java:640) ~[spring-rabbit-2.3.11.jar!/:2.3.11]
```

So what needs to be done for consumers of rabbitmq to connect to rabbitmq-server on TLS-Port(5671) using amqproxy?

**Comment by carlhoerberg** [comment]
Dont connect with SSL/TLS to amqproxy. And also, rotate your credentials you posted above.

**Comment by SyedsImran** [comment]
Values/credentials mention above are just sample values/credentials and are not exact/correct values.

Our rabbitmq is open/running on secure SSL/TLS port 5671 and we can't use non-ssl, unsecure rabbitmq port 5672 for applications/rabbitmq-consumers to connect to it.
We followed this [link](https://www.alibabacloud.com/help/en/message-queue-for-rabbitmq/latest/use-amqproxy-to-solve-connection-reuse-issues-of-clients-such-as-a-php-client) for working for with amqp.

If we use below syntax it will connect to our rabbitmq on secure ssl/tls port 5671 using secure ```amqps```  protocol
```
./amqproxy -l 5.161.156.165 -p 5673 amqps://stg.qtech.com

```
Whereas if we use below syntax  it will try connect to our rabbitmq on non ssl/tls port 5672 using unsecure ```amqp```  protocol which will be of no use of-course as we have not exposed rabbtimq on 5672 port as rabbitmq is not running on it but instead it is running secure 5671 port.
```
./amqproxy -l 5.161.156.165 -p 5673 amqp://stg.qtech.com

```
So again how do we connect to rabbitmq running on secure ssl/tls port 5671 using amqproxy?

**Comment by carlhoerberg** [comment]
In your client, when you connect to the amqproxy you should use AMQP and
port 5673. When amqproxy is run on the same machine as the client the
traffic is local so it's ok.

The error you posted came from your client application, not amqproxy.

**Comment by carlhoerberg** [comment]
Also, why do feel you need amqproxy for a Java Spring application? It should be able to hold long lived connections.

**Comment by SyedsImran** [comment]
Actually we were told to explored how to sent rabbitmq-consumer requests through a proxy using amqp protocol like we do with "HTTPS_PROXY". So we were exploring whether with amqproxy we achieve this or not.
Perhaps we can't, I'm not too sure.

Use-case: We have a requirement where our deployed rabbitmq-consumer application needs to sent requests through a enterprise proxy of a customer to our rabbitmq-server running on SSL/TLS port 5671.

i know this is not the right place to ask this query, but still can the above use-case scenario be achieved through amqproxy?
if not how do we sent amqp protocol requests through a enterprise proxy server?

**Comment by carlhoerberg** [comment]
What's an "enterprise proxy server"? Can you be more technical?

**Comment by SyedsImran** [comment]
Don't know exactly. This is what we got from the customer.

```
All traffic out of this/customer environment is required to go through our Enterprise Proxy (not just any proxy. We're not sure what they're using as of now).
```
Got this below info from the google [link](https://wonderproxy.com/enterprise-proxies)

```

Enterprise proxy server networks
Enterprise proxies are your best bet. You want someone else to be in charge of locating servers in hard-to-reach regions, and you don't want to deal with the never-ending grind of keeping those servers accessible, reliable, and secure. You want enterprise proxies that are available when you need them, where you need them, and you don't want to hire another team of system administrators to get them.

An enterprise proxy server provider caters to a corporate environment.

Server locations are widespread, transparent, and trustworthy, and proxy functionality is robust and reliable.

Support for large and small teams is baked in with Single Sign-On (SSO), batch user management, [Delegated Authentication](https://wonderproxy.com/features/delegated-authentication), and discrete access control.

Your corporate network will integrate seamlessly with the enterprise proxy network, simplifying proxy authentication and enabling tests against your internal staging environments.

Enterprise providers work with your team leads to scope proxy services to your requirements, and work with your finance department to fit within your existing vendor management system.

```
