### ISSUE TITLE
[2.0.0-rc.2] Maximum frame size connection pooling behavior

### ISSUE THREAD

**Issue by SamyDjemai** [cloudamqp/amqproxy#155]
Hi there,

We've noticed an issue in using amqproxy.
We have some applications using `php-amqplib` which has a frame max size of 131,072 bytes, and others using the Node.js `amqplib` library which has a frame max size of 4096 bytes.
Both of these applications connect to our RabbitMQ cluster using amqproxy 2.0.0-rc.2, so their connections are pooled and get a frame max size of 131,072 bytes. As a result, some messages cause the following error on our Node.js applications:
```
Error: Frame size exceeds frame max                                                                                   
    at parseFrame (/home/node/app/node_modules/amqplib/lib/frame.js:55:13)                                            
    at C.recvFrame (/home/node/app/node_modules/amqplib/lib/connection.js:621:15)                                     
    at Socket.go (/home/node/app/node_modules/amqplib/lib/connection.js:486:30)                                       
    at Socket.emit (node:events:514:28)                                                                               
    at Socket.emit (node:domain:489:12)                                                                               
    at emitReadable_ (node:internal/streams/readable:590:12)                                                          
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)                                    
Emitted 'error' event on ChannelModel instance at:                                                                    
    at Connection.emit (node:events:514:28)                                                                           
    at Connection.emit (node:domain:489:12)                                                                           
    at C.onSocketError (/home/node/app/node_modules/amqplib/lib/connection.js:361:10)                                 
    at Connection.emit (node:events:514:28)                                                                           
    at Connection.emit (node:domain:489:12)                                                                           
    at Socket.go (/home/node/app/node_modules/amqplib/lib/connection.js:489:12)                                       
    at Socket.emit (node:events:514:28)                                                                               
    [... lines matching original stack trace ...]                                                                     
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

I believe this issue could be fixed if connections were also pooled based on the requested frame max size.

**Comment by carlhoerberg** [comment]
Yes, or always use framesize 4096 for upstream connections, so that server never tries to send any larger frames down to the client, i think i will do that.
